# Домашнее задание

In [1]:
import numpy as np

## Задача 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [20]:
n = int(input('Введите число: '))
a = np.arange(n)
print(a[::-1])

Введите число: 10
[9 8 7 6 5 4 3 2 1 0]


## Задача 2
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [26]:
n = int(input('Введите число: '))
a = np.arange(n)
b = a[::-1]
c = np.diag(b, k=0)
print(c)
sum_diag = np.trace(c)
print('Сумма значений по диагонали:', sum_diag)

Введите число: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений по диагонали: 45


## Задача 3
Решите систему уравнений:
\begin{equation*}
\LARGE
4x + 2y + z = 4 \\
\LARGE
x + 3y = 12 \\
\LARGE
5y + 4z = -3
\end{equation*}

In [27]:
from numpy import linalg
a = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [0, 5, 4]
])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [28]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Дополнительная задача
Имеется матрица покупок в интернет-магазине:

In [39]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [40]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [41]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [47]:
def search_similar_user (users_stats, next_user_stats):
    """
    Возвращает User ID пользователя, который соответствует 
    самому похожему пользователю для next_user_stats
    
    User ID пользователя - это номер строки в массиве users_stats + 1
    """
    angle_list = []
    for every_user in users_stats:
        angle = cosine(every_user, next_user_stats)
        angle_list.append(1 - angle)
    similar_user = angle_list.index(min(angle_list))
    return similar_user + 1

In [48]:
print(f"Самый похожий пользователь с User ID {search_similar_user (users_stats, next_user_stats)}")

Самый похожий пользователь с User ID 8
